CREATE DATABASE Namedata
USE Namedata
CREATE TABLE DummyTBL (
   ID   INT    NOT NULL,
   Name NVARCHAR (50)     NOT NULL,
);
GO

insert into DummyTBL  (ID, Name) values (1, 'Julieta Priddis');
insert into DummyTBL  (ID, Name) values (2, 'Malissa McShirrie');
insert into DummyTBL  (ID, Name) values (3, 'Lemuel Waywell');
insert into DummyTBL  (ID, Name) values (4, 'Humbert Saynor');
insert into DummyTBL  (ID, Name) values (5, 'Caresse Rickarsey');
insert into DummyTBL  (ID, Name) values (6, 'Sharron Smithin');
insert into DummyTBL  (ID, Name) values (7, 'Rudy Mulderrig');
insert into DummyTBL  (ID, Name) values (8, 'Kermie Huttley');
insert into DummyTBL  (ID, Name) values (9, 'Arlee Metcalfe');
insert into DummyTBL  (ID, Name) values (10, 'Anjanette Gloyens');
insert into DummyTBL  (ID, Name) values (11, 'Nobe Montrose');
insert into DummyTBL  (ID, Name) values (12, 'Kendre Dugald');
insert into DummyTBL  (ID, Name) values (13, 'Virgilio Hyde-Chambers');
insert into DummyTBL  (ID, Name) values (14, 'Lynnet Sciacovelli');
insert into DummyTBL  (ID, Name) values (15, 'Codee Bunten');
insert into DummyTBL  (ID, Name) values (16, 'Nerty Coultish');
insert into DummyTBL  (ID, Name) values (17, 'Benedicta Doubrava');
insert into DummyTBL  (ID, Name) values (18, 'Klara Dalyiel');
insert into DummyTBL  (ID, Name) values (19, 'Myrlene Hellcat');
insert into DummyTBL  (ID, Name) values (20, 'Beckie Gollard');
insert into DummyTBL  (ID, Name) values (21, 'Sheryl Kunzel');
insert into DummyTBL  (ID, Name) values (22, 'Omar Abrashkov');
insert into DummyTBL  (ID, Name) values (23, 'Kelci Barratt');
insert into DummyTBL  (ID, Name) values (24, 'Marillin Boor');
insert into DummyTBL  (ID, Name) values (25, 'Irvin Lawie');
insert into DummyTBL  (ID, Name) values (26, 'Lorettalorna Chapellow');
insert into DummyTBL  (ID, Name) values (27, 'Evaleen Simione');
insert into DummyTBL  (ID, Name) values (28, 'Addi Ivatts');
insert into DummyTBL  (ID, Name) values (29, 'Dmitri Bault');
insert into DummyTBL  (ID, Name) values (30, 'Jo ann Tinline');
insert into DummyTBL  (ID, Name) values (31, 'Veradis Hawkwood');
insert into DummyTBL  (ID, Name) values (32, 'Rusty O''Carroll');
insert into DummyTBL  (ID, Name) values (33, 'Noach Dennert');
insert into DummyTBL  (ID, Name) values (34, 'Marianna Foxall');
insert into DummyTBL  (ID, Name) values (35, 'Winfred Haswall');
insert into DummyTBL  (ID, Name) values (36, 'Allin Faull');
insert into DummyTBL  (ID, Name) values (37, 'Ethel Allmen');
insert into DummyTBL  (ID, Name) values (38, 'Felita Tremberth');
insert into DummyTBL  (ID, Name) values (39, 'Mable Youthed');
insert into DummyTBL  (ID, Name) values (40, 'Eddy Willcock');
insert into DummyTBL  (ID, Name) values (41, 'Sascha Courtliff');
insert into DummyTBL  (ID, Name) values (42, 'Helge Huchot');
insert into DummyTBL  (ID, Name) values (43, 'Marisa Sprowle');
insert into DummyTBL  (ID, Name) values (44, 'Jacinda Hurling');
insert into DummyTBL  (ID, Name) values (45, 'Aili Paddon');
insert into DummyTBL  (ID, Name) values (46, 'Fallon Robke');
insert into DummyTBL  (ID, Name) values (47, 'Kelby Maypole');
insert into DummyTBL  (ID, Name) values (48, 'Joshuah Thorburn');
insert into DummyTBL  (ID, Name) values (49, 'Lev Sircombe');
insert into DummyTBL  (ID, Name) values (50, 'Miguelita Castillon');
insert into DummyTBL  (ID, Name) values (51, 'Caro But');
insert into DummyTBL  (ID, Name) values (52, 'Orson McLay');
insert into DummyTBL  (ID, Name) values (53, 'Darsey Sealey');
insert into DummyTBL  (ID, Name) values (54, 'Marianne Corker');
insert into DummyTBL  (ID, Name) values (55, 'Adriane Stollman');
insert into DummyTBL  (ID, Name) values (56, 'Tye Domenico');
insert into DummyTBL  (ID, Name) values (57, 'Rhona Littlepage');
insert into DummyTBL  (ID, Name) values (58, 'Gardy Hender');
insert into DummyTBL  (ID, Name) values (59, 'Cori Lamborne');
insert into DummyTBL  (ID, Name) values (60, 'Angele Billsberry');
insert into DummyTBL  (ID, Name) values (61, 'Claudia Kirkpatrick');
insert into DummyTBL  (ID, Name) values (62, 'Stanley Slavin');
insert into DummyTBL  (ID, Name) values (63, 'Zollie Hullbrook');
insert into DummyTBL  (ID, Name) values (64, 'Raychel Cancellieri');
insert into DummyTBL  (ID, Name) values (65, 'Kerrin Redgrave');
insert into DummyTBL  (ID, Name) values (66, 'Quinlan Dumbarton');
insert into DummyTBL  (ID, Name) values (67, 'Jackquelin Logan');
insert into DummyTBL  (ID, Name) values (68, 'Kaitlin Pawelke');
insert into DummyTBL  (ID, Name) values (69, 'Gordon Smithson');
insert into DummyTBL  (ID, Name) values (70, 'Denni Maunders');
insert into DummyTBL  (ID, Name) values (71, 'Micky Sleford');
insert into DummyTBL  (ID, Name) values (72, 'Durward Toolin');
insert into DummyTBL  (ID, Name) values (73, 'Ab McGrann');
insert into DummyTBL  (ID, Name) values (74, 'Katrina Quilter');
insert into DummyTBL  (ID, Name) values (75, 'Sloane Gladdolph');
insert into DummyTBL  (ID, Name) values (76, 'Lorrie Butrimovich');
insert into DummyTBL  (ID, Name) values (77, 'Modesta Galway');
insert into DummyTBL  (ID, Name) values (78, 'Cordi Jurca');
insert into DummyTBL  (ID, Name) values (79, 'William Cicci');
insert into DummyTBL  (ID, Name) values (80, 'Terza Corringham');
insert into DummyTBL  (ID, Name) values (81, 'Laurie Lille');
insert into DummyTBL  (ID, Name) values (82, 'Annissa Franz');
insert into DummyTBL  (ID, Name) values (83, 'Dorice Baudacci');
insert into DummyTBL  (ID, Name) values (84, 'Henderson Kenwright');
insert into DummyTBL  (ID, Name) values (85, 'Natale Batterbee');
insert into DummyTBL  (ID, Name) values (86, 'Gwendolin Whitton');
insert into DummyTBL  (ID, Name) values (87, 'Vasili Abernethy');
insert into DummyTBL  (ID, Name) values (88, 'Towny Golby');
insert into DummyTBL  (ID, Name) values (89, 'Carlee Ricold');
insert into DummyTBL  (ID, Name) values (90, 'Cy MacRinn');
insert into DummyTBL  (ID, Name) values (91, 'Sergent Witherop');
insert into DummyTBL  (ID, Name) values (92, 'Ware Ruddle');
insert into DummyTBL  (ID, Name) values (93, 'Gaven Varfalameev');
insert into DummyTBL  (ID, Name) values (94, 'Karlie Keast');
insert into DummyTBL  (ID, Name) values (95, 'Issiah Sygrove');
insert into DummyTBL  (ID, Name) values (96, 'Millard Linger');
insert into DummyTBL  (ID, Name) values (97, 'Armand Quarrell');
insert into DummyTBL  (ID, Name) values (98, 'Kaile Hall');
insert into DummyTBL  (ID, Name) values (99, 'Tabitha Maffezzoli');
insert into DummyTBL  (ID, Name) values (100, 'Ferris Carefull');

GO
